apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gogo-prod

resources:
  - ../../base
  - namespace.yaml
  - pdb.yaml

images:
  - name: gogo
    newName: registry.example.com/platform/gogo
    newTag: 1.0.0

configMapGenerator:
  - name: gogo-config
    behavior: merge
    literals:
      - APP_ENV=prod
      - LOG_LEVEL=info
      - SHUTDOWN_TIMEOUT=20s

patches:
  - path: patch-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: prod
