apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogo
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 256Mi
