apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gogo-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: gogo
    newName: usungu/gogo
    newTag: sha-af8020a8aa51a1c277701f92351fe84c458e7e11

configMapGenerator:
  - name: gogo-config
    behavior: merge
    literals:
      - APP_ENV=dev
      - LOG_LEVEL=debug

patches:
  - path: patch-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: dev
