apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gin-api-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: gogo
    newName: gogo
    newTag: dev

configMapGenerator:
  - name: gin-api-config
    behavior: merge
    literals:
      - APP_ENV=dev
      - LOG_LEVEL=debug

patches:
  - path: patch-deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: dev
