apiVersion: v1
kind: Service
metadata:
  name: gogo
  labels:
    app.kubernetes.io/name: gogo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gogo
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
